### ISSUE TITLE
exit command not found

### ISSUE THREAD

**Issue by koukunwlk** [EnriqueSLeeK/minishell#5]

**Comment by EnriqueSLeeK** [comment]
exit is a builtin not a binary, only the manpages are available for search

**Comment by koukunwlk** [comment]
when minishell execute ``exit`` from command line doesnt exit from current shell
like bash

**Comment by EnriqueSLeeK** [comment]
that's because the `b_exit()` is being called in the child process and not in the parent

**Comment by koukunwlk** [comment]
:octocat: sorry
